version: '3.1'

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MOMGO_INITDB_DATABASE: web

  mongo-express:
    image: mongo-express
    container_name: mongo_admin
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/
    depends_on:
      - mongo

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    image: server
    container_name: server
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mongo
